version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - NODE_ENV=dev
      - PORT=3000
      - LOG_LEVEL=debug
